Repository 9oormthon-univ/2024_DANPOONG_TEAM_16_BE, pull requests merged in 2024-11, with the labels that each got.

#1 chore: 프로젝트 초기 설정
  Mohaeng/.gitattributes
  Mohaeng/.gitignore
  Mohaeng/build.gradle
  Mohaeng/gradle/wrapper/gradle-wrapper.jar
  Mohaeng/gradle/wrapper/gradle-wrapper.properties
  Mohaeng/gradlew
  Mohaeng/gradlew.bat
  Mohaeng/settings.gradle
  Mohaeng/src/main/java/danpoong/mohaeng/MohaengApplication.java
  Mohaeng/src/test/java/danpoong/mohaeng/MohaengApplicationTests.java
Labels: ⚙️ Setting

#3 초기 테이블 생성을 위한 도메인 설계
  Mohaeng/.gitattributes
  Mohaeng/.gitignore
  Mohaeng/build.gradle
  Mohaeng/gradle/wrapper/gradle-wrapper.jar
  Mohaeng/gradle/wrapper/gradle-wrapper.properties
  Mohaeng/gradlew
  Mohaeng/gradlew.bat
  Mohaeng/settings.gradle
  Mohaeng/src/main/java/danpoong/mohaeng/Area/Domain/Area.java
  Mohaeng/src/main/java/danpoong/mohaeng/Area/Repository/AreaRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/Course/Domain/UserCourse.java
  Mohaeng/src/main/java/danpoong/mohaeng/Course/Repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/Disabled/Domain/Disabled.java
  Mohaeng/src/main/java/danpoong/mohaeng/Disabled/Repository/DisabledRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/Location/Domain/Location.java
  Mohaeng/src/main/java/danpoong/mohaeng/Location/Repository/LocationRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/MohaengApplication.java
  Mohaeng/src/test/java/danpoong/mohaeng/MohaengApplicationTests.java
  README.md
Labels: ⚙️ Setting, ✨ Feature

#5 [Refactor/#4]: 도메인 수정 및 생성
  Mohaeng/src/main/java/danpoong/mohaeng/Area/Domain/Area.java
  Mohaeng/src/main/java/danpoong/mohaeng/Course/Domain/Course.java
  Mohaeng/src/main/java/danpoong/mohaeng/Course/Domain/UserCourse.java
  Mohaeng/src/main/java/danpoong/mohaeng/Disabled/Domain/Disabled.java
  Mohaeng/src/main/java/danpoong/mohaeng/Location/Domain/Location.java
  Mohaeng/src/main/java/danpoong/mohaeng/area/domain/Area.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/Disability.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/UserDisability.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/TripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/UserTripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/domain/User.java
Labels: 🔨 Refactor

#10 [Refactor] 패키지명 정리
  Mohaeng/src/main/java/danpoong/mohaeng/area/repository/AreaRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/Course.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/UserCourse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/disabled/domain/Disabled.java
  Mohaeng/src/main/java/danpoong/mohaeng/disabled/repository/DisabledRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/domain/Location.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepository.java
Labels: ⚙️ Setting, 🔨 Refactor

#11 [Feat/#8] 사용자 정보 생성 API
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserController.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/dto/UserCreateReq.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/repository/UserRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/service/UserService.java
Labels: ✨ Feature

#14 [Feat/#9] 유저 존재 확인 API
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserController.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/service/UserService.java
Labels: ✨ Feature

#15 기본 설정, User 관련 배포
  Mohaeng/.gitignore
  Mohaeng/build.gradle
  Mohaeng/src/main/java/danpoong/mohaeng/area/domain/Area.java
  Mohaeng/src/main/java/danpoong/mohaeng/area/repository/AreaRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/config/SwaggerConfig.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/Course.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/UserCourse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/Disability.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/UserDisability.java
  Mohaeng/src/main/java/danpoong/mohaeng/disabled/domain/Disabled.java
  Mohaeng/src/main/java/danpoong/mohaeng/disabled/repository/DisabledRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/domain/Location.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/TripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/UserTripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserController.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/domain/User.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/dto/UserCreateReq.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/repository/UserRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/service/UserService.java
Labels: 🌏 Deploy

#19 [Feat/#17] 관광지 상세 정보 조회 API
  Mohaeng/src/main/java/danpoong/mohaeng/location/controller/LocationController.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/controller/LocationControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/dto/LocationInfoRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/service/LocationService.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
Labels: ✨ Feature

#20 [Deploy/#18, #19] 데이터 복원, 관광지 상세 정보 조회
  Mohaeng/src/main/java/danpoong/mohaeng/area/domain/Area.java
  Mohaeng/src/main/java/danpoong/mohaeng/disabled/domain/Disabled.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/controller/LocationController.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/controller/LocationControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/dto/LocationInfoRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/service/LocationService.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
Labels: ✨ Feature, 🔨 Refactor

#21 [Feat] TTS 서비스를 위한 화면 이미지 설명 API
  Mohaeng/src/main/java/danpoong/mohaeng/tts/config/OpenAIConfig.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/controller/TTSController.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/Message.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/TextMessage.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/request/Content.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/request/ImageContent.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/request/ImageMessage.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/request/ImageUrl.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/request/TTSRequest.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/request/TextContent.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/response/Choice.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/dto/response/TTSResponse.java
  Mohaeng/src/main/java/danpoong/mohaeng/tts/service/TTSService.java
Labels: ✨ Feature

#23 [Feat/#22] 코스 등록 API
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseController.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/Course.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/UserCourse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseCreateReq.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseCreateRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/CourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/Disability.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/UserDisability.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/repository/DisabilityRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/repository/UserDisabilityRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/controller/LocationController.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/controller/LocationControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/TripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/UserTripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserController.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/repository/UserRepository.java
Labels: ✨ Feature, 🔨 Refactor

#25 [Refactor/#22] 코스 여행 취향 정보 저장 로직 추가
  Mohaeng/src/main/java/danpoong/mohaeng/course/domain/Course.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/domain/UserDisability.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/domain/TripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/domain/UserTripType.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/repository/TripTypeRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/repository/UserTripTypeRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/domain/User.java
Labels: 🔨 Refactor

#26 [Feat] 코스번호를 통해 코스 삭제 기능
  .github/workflows/main.yml
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/repository/UserDisabilityRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/trip_type/repository/UserTripTypeRepository.java
  deploy.sh
Labels: ✨ Feature

#28 [Chore] Cors Config 허용
  Mohaeng/src/main/java/danpoong/mohaeng/config/WebConfig.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: ⚙️ Setting

#32 [Feat] AI 추천 코스 API
  Mohaeng/build.gradle
  Mohaeng/src/main/java/danpoong/mohaeng/config/QueryDSLConfig.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseController.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/AICourseRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/ChatGPTRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/Choice.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/Message.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/domain/Location.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepositoryCustom.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepositoryImpl.java
Labels: ✨ Feature

#33 [Feat] 코스 번호를 통해 코스 상세정보 조회 기능
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseSearchResponse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: ✨ Feature

#34 [Fix] Merge 버그 해결
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🐞 BugFix

#35 [Deploy] AI 코스추천, 코스 상세정보 조회
  Mohaeng/build.gradle
  Mohaeng/src/main/java/danpoong/mohaeng/config/QueryDSLConfig.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseController.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/AICourseRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/ChatGPTRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/Choice.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseSearchResponse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/Message.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/domain/Location.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepositoryCustom.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepositoryImpl.java
Labels: 🌏 Deploy

#38 [Feat/#37] 유저 코스 목록 조회
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/CourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserController.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/controller/UserControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/dto/UserCourseRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/service/UserService.java
Labels: ✨ Feature

#40 [chore]netlify 연결 허용
  Mohaeng/src/main/java/danpoong/mohaeng/config/WebConfig.java
Labels: ⚙️ Setting

#41 [Refactor] AI 추천 코스 조회 -> 저장
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseController.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/AICourseReq.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/CourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🔨 Refactor

#42 [Deploy] AI 추천 코스 로직 변경 사항
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseController.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/AICourseReq.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/CourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🌏 Deploy

#43 [Refactor] AI 추천 코스 등록 API 수정
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseController.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/controller/CourseControllerImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseCreateReq.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/repository/UserDisabilityRepository.java
Labels: 🔨 Refactor

#46 [refactor]코스 관광지 일정 별 응답값 추가
  Mohaeng/src/main/java/danpoong/mohaeng/config/WebConfig.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseSearchResponse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🔨 Refactor

#48 [Refactor] 유저 코스 목록 조회 API
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepositoryImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/dto/UserCourseRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/service/UserService.java
Labels: 🔨 Refactor

#49 [Deploy] 유저 코스 목록 조회 API
  Mohaeng/src/main/java/danpoong/mohaeng/course/repository/UserCourseRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepositoryImpl.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/dto/UserCourseRes.java
  Mohaeng/src/main/java/danpoong/mohaeng/user/service/UserService.java
Labels: 🌏 Deploy

#51 [Refactor] 유저 코스 상세 정보 조회 수정
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseSearchResponse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🔨 Refactor

#52 [Deploy] 유저 코스 상세 정보 조회 수정
  Mohaeng/src/main/java/danpoong/mohaeng/course/dto/CourseSearchResponse.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🔨 Refactor

#53 [Refactor] AI 추천 코스 프롬프트 최적화
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🔨 Refactor

#54 [Deploy] AI 추천 코스 프롬프트 최적화
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
Labels: 🔨 Refactor

#55 [Refactor] AI 추천 코스 프롬프트 최적화 및 존재하지 않는 장소 제거
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
Labels: 🔨 Refactor

#56 [Deploy] AI 추천 코스 프롬프트 최적화 및 존재하지 않는 장소 제거
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
Labels: 🌏 Deploy

#57 [Refactor] : AI 추천 코스 프롬프트 최적화
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
Labels: 🔨 Refactor

#58 [Refactor] 유저 코스 상세 정보 조회
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/AIRecService.java
  Mohaeng/src/main/java/danpoong/mohaeng/course/service/CourseService.java
  Mohaeng/src/main/java/danpoong/mohaeng/disability/repository/DisabilityRepository.java
Labels: 🔨 Refactor

#59 [Feat] 데이터 구축 관련 API
  Mohaeng/src/main/java/danpoong/mohaeng/data/controller/DataController.java
  Mohaeng/src/main/java/danpoong/mohaeng/data/service/SettingAreaService.java
  Mohaeng/src/main/java/danpoong/mohaeng/data/service/SettingLocationService.java
  Mohaeng/src/main/java/danpoong/mohaeng/data/util/JsonParsingUtil.java
  Mohaeng/src/main/java/danpoong/mohaeng/disabled/repository/DisabledRepository.java
  Mohaeng/src/main/java/danpoong/mohaeng/location/repository/LocationRepository.java
Labels: ✨ Feature
